# Configuration for the CSU-IR pre-training script

paths:
  output_dir: check_points/Multi-stage_training_Stage_I_MD
  tokenizer: model/tokenizer-smiles-roberta-1e_new
  train_smiles: data/Multi-staged_training_data/Molecular dynamics simulation data/Multimodal_Spectroscopic_Library_train_smiles.txt
  train_ir: data/Multi-staged_training_data/Molecular dynamics simulation data/Multimodal_Spectroscopic_Library_train_ir.pt
  val_smiles: data/Multi-staged_training_data/Molecular dynamics simulation data/Multimodal_Spectroscopic_Library_val_smiles.txt
  val_ir: data/Multi-staged_training_data/Molecular dynamics simulation data/Multimodal_Spectroscopic_Library_val_ir.pt
  test_smiles: data/Multi-staged_training_data/Molecular dynamics simulation data/Multimodal_Spectroscopic_Library_test_smiles.txt
  test_ir: data/Multi-staged_training_data/Molecular dynamics simulation data/Multimodal_Spectroscopic_Library_test_ir.pt

model_params:
  smiles_model:
    smiles_maxlen: 300
    max_position_embeddings: 505
    vocab_size: 181
    feature_dim: 768
  ir_model:
    output_channels: 768
    channels: 32
    dim: 1024
    no_txtnorm: false

training_params:
  num_epochs: 80
  device: auto

dataloader_params:
  batch_size: 208
  num_workers: 0

optimizer_params:
  learning_rate: 5.0e-5  # YAML handles scientific notation well
  weight_decay: 1.0e-4

scheduler_params:
  warmup_epochs: 10

model_save_params:
  num_best_models: 1
  loss_log_file: loss_data.json
